title: CheolJun Park
description: >
  CheolJun Park
    - KAIST EE PhD Student @SYSEC Lab
#copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://unrloay2.github.io
disqus_shortname: 
facebook_username: cheoljun.park.1
#twitter_username: "#"
#linkedin_username: "#"
instagram_username: cheoljjjun
#pinterest_username:
#flickr_username:
github_username: unrloay2 "#"
#feed_icon: rss
email: fermioncj@mkaist.ac.kr "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 6
