# Site settings
title: CheolJun Park
description: 'Ph.D Student @ KAIST EE'
url: 'https://unrloay2.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'CheolJun Park'
  email: fermioncj@kaist.ac.kr
#  twitter_username: joshgerdes
  facebook_username: cheoljun.park.1
  github_username:  unrloay2
#  linkedin_username:  joshgerdes
  instagram_username: cheoljjjun

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
